title: 'CTS-NL'

slogan: 'Computer Technology Society Newfoundland Labrador'

description: 'A community for the people who work in or have an interest in software development, programming, information technology and computing in Newfoundland and Labrador'

credits: '<p>Created with &hearts; by <a href="http://phlow.de/">Phlow</a> with <a href="http://jekyllrb.com/" target="_blank">Jekyll</a> based on <a href="http://phlow.github.io/feeling-responsive/">Feeling Responsive</a>.</p>'

author: mitmaro

url: 'https://ctsnl.ca'
baseurl: ''

improve_content: https://github.com/CTS-NL/CTS-NL.github.io/edit/gh-pages

# This URL points directly to the images directory making
# things easier to link to images in posts and templates. It needs a slash at the end.
urlimg: '//ctsnl.ca/images/'

# Logo size is 600x80 pixels
logo: "logo.png"

plugins:
    - jekyll-gist
    - jekyll-paginate

paginate: 5
paginate_path: "/news/:num/"

markdown: kramdown
highlight: rouge
excerpt_separator: "<!--more-->"
include: ['.htaccess']
# Exclude these files from your production _site
exclude:
    - .sass-cache
    - .idea
    - docker-compose.yml
    - Gemfile
    - Gemfile.lock
    - INSTALL.md
    - LICENSE
    - README.md
    - server.sh
    - vendor/bundle
    - ValidateJobs.py
    - ParseJobs.py
    - Pipfile
    - Pipfile.lock

# ignore the date
future: true

# The language setting is used in /includes/header.html for html-settings
language: 'en'

# Used › default.html front-matter and compress.html
# Options › http://jch.penibelst.de
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  profile: false
  ignore:
    envs: [development]

defaults:
  -
    scope:
      path: ''
      type: 'pages'
    values:
      show_meta: false
      sidebar: 'right'
      author: mitmaro
  -
    scope:
      path: ''
      type: 'posts'
    values:
      show_meta: true
      sidebar: 'left'
      author: mitmaro

socialmedia:
    twitter: CTS_NL
    facebook:


#      _____
#     / ___/____ ___________
#     \__ \/ __ `/ ___/ ___/
#    ___/ / /_/ (__  |__  )     More › http://sass-lang.com/
#   /____/\__,_/____/____/      More › http://jekyllrb.com/docs/assets/#sassscss
#

sass:
    sass_dir: _sass
    style: :compressed
