jekyll:
    image: jekyll/jekyll
    command: jekyll serve --watch --config _config.yml,_config_dev.yml
    ports:
        - 4000:4000
    volumes:
        - .:/srv/jekyll
        - ./vendor/bundle:/usr/local/bundle
