jobs:
- company: aucure
  jobs:
    current:
    - link: https://navy-pixie-5a8.notion.site/Software-Developer-16556f12163e40a38d2a757ff1cb07ff
      remote: false
      title: Software Developer
    - link: https://navy-pixie-5a8.notion.site/Frontend-Developer-24bc860a15ba4b7793e60f03833aaf25
      remote: false
      title: Frontend Developer
    previous: []
- company: kraken
  jobs:
    current:
    - link: https://krakenrobotics.com/themencode-pdf-viewer/?file=https://krakenrobotics.com/wp-content/uploads/2024/06/Kraken-Robotics-Careers-Opportunity-Senior-Software-Developer-KRSI-2024-04.pdf
      remote: false
      title: Senior Software Developer
    previous:
    - link: https://krakenrobotics.com/wp-content/uploads/2023/11/Kraken-Robotics-Software-Project-Manager-KRSI-2023-30.pdf
      remote: false
      title: Software Project Manager
- company: mysa
  jobs:
    current: []
    previous:
    - link: https://jobs.lever.co/getmysa/0849acf1-6f41-4b9c-87c1-38c3c87497e9
      remote: false
      title: Senior Data & Analytics Specialist
- company: govnl
  jobs:
    current: []
    previous:
    - link: https://www.hiring.gov.nl.ca/job-details/29830
      remote: false
      title: Senior Programmer Analyst
- company: solace
  jobs:
    current: []
    previous:
    - link: https://www.solace.ca/careers/software-developer
      remote: false
      title: Software Developer
- company: milkmoovement
  jobs:
    current: []
    previous:
    - link: https://jobs.lever.co/milk-moovement/046de99e-0f80-468b-be6d-7eb2f9c394b4
      remote: false
      title: Senior Full Stack Developer
    - link: https://jobs.lever.co/milk-moovement/238d9455-d580-4a62-852f-b805be949404
      remote: false
      title: Intermediate Full Stack Developer
- company: stantec
  jobs:
    current: []
    previous:
    - link: https://stantec.jobs/st-john-s-nl/senior-software-developer/497F4305381B46B799B03D2BE0A0F926/job/
      remote: false
      title: Senior Software Developer
- company: bluecross
  jobs:
    current: []
    previous:
    - link: https://jobs.medaviebc.ca/job/_/574751917/
      remote: true
      title: Sr. SharePoint Developer
- company: colab
  jobs:
    current: []
    previous:
    - link: https://boards.greenhouse.io/colabsoftware/jobs/4001134008
      remote: false
      title: Senior Developer
- company: ican
  jobs:
    current: []
    previous:
    - link: https://icanmarine.com/careers/
      remote: false
      title: Software Developers
- company: trophiai
  jobs:
    current: []
    previous:
    - link: https://trophiai.bamboohr.com/careers/31
      remote: false
      title: Sr. Game Developer
    - link: https://trophiai.bamboohr.com/careers/35
      remote: false
      title: Sr. Software Developer
- company: smartdoor
  jobs:
    current: []
    previous:
    - link: https://smartdoor.ai/careers?_hsmi=266009684
      remote: false
      title: Senior/Junior Software Developers
- company: spellbook
  jobs:
    current: []
    previous:
    - link: https://rallynow.freshteam.com/jobs/wq8HSn3O1Tdx/full-stack-engineer
      remote: false
      title: Full-Stack Engineer
- company: vmt
  jobs:
    current: []
    previous:
    - link: https://www.virtualmarine.ca/careers
      remote: false
      title: Game Developer
    - link: https://www.virtualmarine.ca/careers
      remote: false
      title: Software Developer
- company: strobeltek
  jobs:
    current: []
    previous:
    - link: https://strobeltek.com/careers/
      remote: false
      title: Software Engineer/Mid Electrical
    - link: https://strobeltek.com/careers/
      remote: false
      title: Senior Software Developer
- company: compusult
  jobs:
    current: []
    previous:
    - link: https://www.compusult.com/web/guest/careers
      remote: false
      title: Software Developers
- company: avalonholo
  jobs:
    current: []
    previous:
    - link: https://www.avalonholographics.com/careers
      remote: false
      title: FPGA Designer
    - link: https://www.avalonholographics.com/careers
      remote: false
      title: Software Engineer
- company: ioa
  jobs:
    current: []
    previous:
    - link: https://ioass.com/careers-1
      remote: false
      title: Programmer / Analyst
newPostings: true
updateDate: 2024-07-04
