jobs:
- company: quorum
  jobs:
    current:
    - link: https://workforcenow.adp.com/mascsr/default/mdf/recruitment/recruitment.html?cid=978f4299-eee2-4d9e-a9e2-51a1c0ba3aad&ccId=19000101_000001&jobId=437810
      remote: true
      title: Senior Developer
    previous: []
- company: verafin
  jobs:
    current:
    - link: https://jobs.lever.co/verafin/3bc138b5-23da-4551-a320-d504b267d9ef
      remote: true
      title: Quality Assurance Analyst
    - link: https://jobs.lever.co/verafin/ad6036fd-40d6-41b5-8939-3328f707d44f
      remote: true
      title: Front-End Software Engineer
    - link: https://jobs.lever.co/verafin/a73a0198-4803-4904-8f36-3eaccad1a38a
      remote: true
      title: Back-End Software Engineer
    previous: []
- company: milkmoovement
  jobs:
    current:
    - link: https://jobs.lever.co/milk-moovement/ac085e0d-2dda-4064-9ab7-2533f4560711
      remote: true
      title: Mobile Developer II
    previous: []
- company: zorbits
  jobs:
    current:
    - link: https://www.paycomonline.net/v4/ats/web.php/jobs/ViewJobDetails?job=86682&clientkey=5A4F90A76FC25176D905F555FF2C8ACC
      remote: false
      title: Junior Back End Web Developer
    previous: []
- company: fonemed
  jobs:
    current: []
    previous:
    - link: https://fonemed.applytojob.com/apply/redo4NN4Jy/Quality-Assurance-Analyst
      remote: true
      title: Quality Assurance Analyst
- company: instrumar
  jobs:
    current: []
    previous:
    - link: https://technl.ca/job/full-stack-developer-2/
      remote: false
      title: Full Stack Developer
- company: mariner
  jobs:
    current: []
    previous:
    - link: https://www.smartrecruiters.com/MarinerPartnersInc/743999897256165-as-400-mainframe-system-analyst-contract-position-
      remote: true
      title: AS/400 Mainframe System Analyst
    - link: https://www.smartrecruiters.com/MarinerPartnersInc/743999894850765-senior-java-full-stack-developer
      remote: true
      title: Senior Java Full Stack Developer
    - link: https://www.smartrecruiters.com/MarinerPartnersInc/743999834056922--net-developer
      remote: true
      title: .NET Developer
    - link: https://www.smartrecruiters.com/MarinerPartnersInc/743999799612047-senior-python-developer
      remote: true
      title: Senior Python Developer
- company: vish
  jobs:
    current: []
    previous:
    - link: https://getvish.com/about-vish/careers/#1680635740361-b13703b3-811d
      remote: false
      title: Senior Functional Developer (Scala)
    - link: https://getvish.com/about-vish/careers/#1680636072541-93bed6c6-9058
      remote: false
      title: Senior Frontend Developer
- company: intactlab
  jobs:
    current: []
    previous:
    - link: https://careers.intactfc.com/ca/en/job/R132664
      remote: false
      title: Backend Java Developer (Senior/Intermediate)
    - link: https://careers.intactfc.com/ca/en/job/R130696
      remote: false
      title: Manager, Software Development
    - link: https://careers.intactfc.com/ca/en/job/R132677
      remote: false
      title: Android Developer (Senior/Specialist/Tech Lead)
- company: vision33
  jobs:
    current: []
    previous:
    - link: https://jobs.vision33.com/careers/31076-Vision33/jobs/15903044-Developer-Saltbox
      remote: false
      title: Developer
    - link: https://jobs.vision33.com/careers/31076-Vision33/jobs/13154698-Software-Developer-General-Application
      remote: false
      title: Software Developer
- company: kraken
  jobs:
    current: []
    previous:
    - link: https://krakenstaging.wpsc.dev/wp-content/uploads/2023/04/Kraken-Robotics-Software-Developers-KRSI-2023-01.pdf
      remote: false
      title: Software Developers
    - link: https://krakenrobotics.com/themencode-pdf-viewer/?file=https://krakenrobotics.com/wp-content/uploads/2023/04/Kraken-Robotics-Firmware-Engineer-KRSI-2023-04.pdf
      remote: false
      title: Firmware Engineer
- company: opasmobile
  jobs:
    current: []
    previous:
    - link: https://technl.ca/job/opas-mobile-st-johns-nl-remote-options-full-time-contract-part-time-temporary-junior-intermediate-backend-developer-nodejs/
      remote: false
      title: Junior/Intermediate Backend Developer (NodeJS)
    - link: https://technl.ca/job/opas-mobile-st-johns-nl-remote-options-full-time-contract-part-time-temporary-junior-intermediate-react-native-developer/
      remote: false
      title: Junior/Intermediate React Native Developer
- company: sequencebio
  jobs:
    current: []
    previous:
    - link: https://sequencebio.bamboohr.com/careers/54
      remote: true
      title: Bioinformatician
    - link: https://sequencebio.bamboohr.com/careers/53
      remote: true
      title: Computational Biologist
    - link: https://sequencebio.bamboohr.com/careers/48
      remote: true
      title: Security Analyst
    - link: https://sequencebio.bamboohr.com/careers/49
      remote: true
      title: Cloud Developer
    - link: https://sequencebio.bamboohr.com/careers/46
      remote: true
      title: Web Application Developer
    - link: https://sequencebio.bamboohr.com/careers/47
      remote: true
      title: Experienced AWS Infrastructure Engineer
- company: vmt
  jobs:
    current: []
    previous:
    - link: https://www.virtualmarine.ca/careers
      remote: false
      title: Game Developer
    - link: https://www.virtualmarine.ca/careers
      remote: false
      title: Software Developer
    - link: https://www.virtualmarine.ca/careers
      remote: false
      title: Software Developer - Machine Learning
- company: inspectar
  jobs:
    current: []
    previous:
    - link: https://www.inspectar.com/career/qa-engineer-co-op-student
      remote: false
      title: QA Engineer CO-OP Student
    - link: https://www.inspectar.com/career/software-developer-co-op-student
      remote: false
      title: Software Developer CO-OP Student
    - link: https://www.inspectar.com/career/c-sharp-developer
      remote: false
      title: C# Developer
    - link: https://www.inspectar.com/career/sr-unity-developer
      remote: false
      title: Senior Unity Developer
- company: easternhealth
  jobs:
    current: []
    previous:
    - link: https://employment.easternhealth.ca/eRecruit/VacancyDetail.aspx?VacancyUID=000000089318
      remote: true
      title: Computer Programmer/Analyst
- company: strobeltek
  jobs:
    current: []
    previous:
    - link: https://strobeltek.com/careers/
      remote: false
      title: Software Engineer/Mid Electrical
    - link: https://strobeltek.com/careers/
      remote: false
      title: Senior Software Developer
- company: bluecross
  jobs:
    current: []
    previous:
    - link: https://jobs.medaviebc.ca/job/_/559366117/
      remote: true
      title: Test Automation Architect
- company: otherocean
  jobs:
    current: []
    previous:
    - link: https://otherocean.com/jobs/Senior_Programmer.pdf
      remote: true
      title: Senior Programmer
- company: compusult
  jobs:
    current: []
    previous:
    - link: https://www.compusult.com/web/guest/careers
      remote: false
      title: Software Developers
- company: avalonholo
  jobs:
    current: []
    previous:
    - link: https://www.avalonholographics.com/careers
      remote: false
      title: FPGA Designer
    - link: https://www.avalonholographics.com/careers
      remote: false
      title: Software Engineer
- company: ioa
  jobs:
    current: []
    previous:
    - link: https://ioass.com/careers-1
      remote: false
      title: Programmer / Analyst
newPostings: true
updateDate: 2023-04-27
