jobs:
- company: verafin
  jobs:
    current:
    - link: https://jobs.lever.co/verafin/c76aa616-4cbe-438d-a9ab-354785443b9c
      remote: false
      title: Software Developer
    - link: https://jobs.lever.co/verafin/e82cd562-70cc-4362-a193-f1e011942c12
      remote: false
      title: Senior Software Developer
    - link: https://jobs.lever.co/verafin/f239034c-0895-48d2-a7b1-dabf8982355b
      remote: false
      title: Senior Software Developer - Remote Canada
    previous: []
- company: milkmoovement
  jobs:
    current:
    - link: https://jobs.lever.co/milk-moovement/c334a35a-ae61-4a10-b6cf-04b094c59b98
      remote: false
      title: Mobile Developer II
    previous:
    - link: https://jobs.lever.co/milk-moovement/16221e87-bbc9-4718-aa54-3f3ce63edbd3
      remote: false
      title: Full Stack Developer III
- company: bluecross
  jobs:
    current: []
    previous:
    - link: https://jobs.medaviebc.ca/job/_/574838417/
      remote: false
      title: Sr. Programmer Analyst
    - link: https://jobs.medaviebc.ca/job/_/574841717/
      remote: false
      title: Sr. Programmer/Analyst
    - link: https://jobs.medaviebc.ca/job/_/574751917/
      remote: false
      title: Sr. SharePoint Developer
- company: mysa
  jobs:
    current: []
    previous:
    - link: https://jobs.lever.co/getmysa/22e227c4-a04c-4624-a161-eb6e3f18c5f4
      remote: false
      title: Senior DevOps Engineer
    - link: https://jobs.lever.co/getmysa/1961d763-b636-4519-9cfb-0f04dd1025e1
      remote: false
      title: Senior Full Stack Developer
- company: stantec
  jobs:
    current: []
    previous:
    - link: https://stantec.jobs/st-johns-nl/application-developer/B821030CB29540F4A69C9227202CC289/job/
      remote: false
      title: Application Developer
- company: mobia
  jobs:
    current: []
    previous:
    - link: https://can231.dayforcehcm.com/CandidatePortal/en-US/mobia/Posting/View/10516
      remote: true
      title: Senior Microsoft Azure Engineers
- company: smartdoor
  jobs:
    current: []
    previous:
    - link: https://smartdoor.ai/careers?_hsmi=266009684
      remote: false
      title: Senior/Junior Software Developers
- company: nlhydro
  jobs:
    current: []
    previous:
    - link: https://www.nlh.nl.ca/HydroWeb/NLHydroWeb.nsf/LookupJobPostingsExternal/NLH-RE-23-113?OpenDocument
      remote: false
      title: Software Specialist
- company: trophiai
  jobs:
    current: []
    previous:
    - link: https://trophiai.bamboohr.com/careers/35
      remote: false
      title: Sr. Software Developer
    - link: https://trophiai.bamboohr.com/careers/40
      remote: false
      title: UX/UI Designer
    - link: https://trophiai.bamboohr.com/careers/31
      remote: false
      title: Sr. Game Developer
- company: spellbook
  jobs:
    current: []
    previous:
    - link: https://rallynow.freshteam.com/jobs/wq8HSn3O1Tdx/full-stack-engineer
      remote: false
      title: Full-Stack Engineer
- company: vish
  jobs:
    current: []
    previous:
    - link: https://getvish.com/about-vish/careers/#1680635740361-b13703b3-811d
      remote: false
      title: Senior Functional Developer (Scala)
    - link: https://getvish.com/about-vish/careers/#1680636072541-93bed6c6-9058
      remote: false
      title: Senior Frontend Developer
- company: colab
  jobs:
    current: []
    previous:
    - link: https://colabsoftware.applytojobs.ca/revops/25191
      remote: false
      title: Revenue Operations Software Developer
- company: kraken
  jobs:
    current: []
    previous:
    - link: https://krakenstaging.wpsc.dev/wp-content/uploads/2023/04/Kraken-Robotics-Software-Developers-KRSI-2023-01.pdf
      remote: false
      title: Software Developers
    - link: https://krakenrobotics.com/themencode-pdf-viewer/?file=https://krakenrobotics.com/wp-content/uploads/2023/04/Kraken-Robotics-Firmware-Engineer-KRSI-2023-04.pdf
      remote: false
      title: Firmware Engineer
- company: vmt
  jobs:
    current: []
    previous:
    - link: https://www.virtualmarine.ca/careers
      remote: false
      title: Game Developer
    - link: https://www.virtualmarine.ca/careers
      remote: false
      title: Software Developer
    - link: https://www.virtualmarine.ca/careers
      remote: false
      title: Software Developer - Machine Learning
- company: vision33
  jobs:
    current: []
    previous:
    - link: https://jobs.vision33.com/careers/31076-Vision33/jobs/13154698-Software-Developer-General-Application
      remote: false
      title: Software Developer
- company: inspectar
  jobs:
    current: []
    previous:
    - link: https://www.inspectar.com/career/qa-engineer-co-op-student
      remote: false
      title: QA Engineer CO-OP Student
    - link: https://www.inspectar.com/career/software-developer-co-op-student
      remote: false
      title: Software Developer CO-OP Student
    - link: https://www.inspectar.com/career/c-sharp-developer
      remote: false
      title: C# Developer
    - link: https://www.inspectar.com/career/sr-unity-developer
      remote: false
      title: Senior Unity Developer
- company: easternhealth
  jobs:
    current: []
    previous:
    - link: https://employment.easternhealth.ca/eRecruit/VacancyDetail.aspx?VacancyUID=000000089318
      remote: true
      title: Computer Programmer/Analyst
- company: sequencebio
  jobs:
    current: []
    previous:
    - link: https://sequencebio.bamboohr.com/careers/60
      remote: false
      title: Cloud Developer
- company: strobeltek
  jobs:
    current: []
    previous:
    - link: https://strobeltek.com/careers/
      remote: false
      title: Software Engineer/Mid Electrical
    - link: https://strobeltek.com/careers/
      remote: false
      title: Senior Software Developer
- company: otherocean
  jobs:
    current: []
    previous:
    - link: https://otherocean.com/jobs/Senior_Programmer.pdf
      remote: true
      title: Senior Programmer
- company: compusult
  jobs:
    current: []
    previous:
    - link: https://www.compusult.com/web/guest/careers
      remote: false
      title: Software Developers
- company: avalonholo
  jobs:
    current: []
    previous:
    - link: https://www.avalonholographics.com/careers
      remote: false
      title: FPGA Designer
    - link: https://www.avalonholographics.com/careers
      remote: false
      title: Software Engineer
- company: ioa
  jobs:
    current: []
    previous:
    - link: https://ioass.com/careers-1
      remote: false
      title: Programmer / Analyst
newPostings: true
updateDate: 2023-10-12
