jobs:
- company: siftmed
  jobs:
    current:
    - link: https://www.linkedin.com/jobs/view/3547294833
      remote: true
      title: Senior Full Stack Developer
    previous: []
- company: mariner
  jobs:
    current:
    - link: https://www.smartrecruiters.com/MarinerPartnersInc/743999897256165-as-400-mainframe-system-analyst-contract-position-
      remote: true
      title: AS/400 Mainframe System Analyst
    previous:
    - link: https://www.smartrecruiters.com/MarinerPartnersInc/743999894850765-senior-java-full-stack-developer
      remote: true
      title: Senior Java Full Stack Developer
    - link: https://www.smartrecruiters.com/MarinerPartnersInc/743999834056922--net-developer
      remote: true
      title: .NET Developer
    - link: https://www.smartrecruiters.com/MarinerPartnersInc/743999799612047-senior-python-developer
      remote: true
      title: Senior Python Developer
- company: govnl
  jobs:
    current:
    - link: https://www.hiring.gov.nl.ca/Jobs.aspx/Details/27741
      remote: false
      title: Database Analyst
    previous: []
- company: vish
  jobs:
    current:
    - link: https://getvish.com/about-vish/careers/#1680635740361-b13703b3-811d
      remote: false
      title: Senior Functional Developer (Scala)
    - link: https://getvish.com/about-vish/careers/#1680636072541-93bed6c6-9058
      remote: false
      title: Senior Frontend Developer
    previous: []
- company: radient
  jobs:
    current: []
    previous:
    - link: https://ca.indeed.com/viewjob?jk=88a12e5a921ba347
      remote: true
      title: Software Quality Assurance Specialist
- company: intactlab
  jobs:
    current: []
    previous:
    - link: https://careers.intactfc.com/ca/en/job/R132664
      remote: false
      title: Backend Java Developer (Senior/Intermediate)
    - link: https://careers.intactfc.com/ca/en/job/R130564
      remote: false
      title: Senior Salesforce Developer
    - link: https://careers.intactfc.com/ca/en/job/R130696
      remote: false
      title: Manager, Software Development
    - link: https://careers.intactfc.com/ca/en/job/R132677
      remote: false
      title: Android Developer (Senior/Specialist/Tech Lead)
    - link: https://careers.intactfc.com/ca/en/job/R132678/iOS-Developer-Senior-Specialist-Tech-Lead
      remote: false
      title: iOS Developer (Senior/Specialist/Tech Lead)
    - link: https://careers.intactfc.com/ca/en/job/R132675
      remote: false
      title: Java Technical Lead
- company: vision33
  jobs:
    current: []
    previous:
    - link: https://jobs.vision33.com/careers/31076-Vision33/jobs/15903044-Developer-Saltbox
      remote: false
      title: Developer
    - link: https://jobs.vision33.com/careers/31076-Vision33/jobs/13154698-Software-Developer-General-Application
      remote: false
      title: Software Developer
- company: kraken
  jobs:
    current: []
    previous:
    - link: https://jobs.careerbeacon.com/details/software-developers/1876443
      remote: false
      title: Software Developers
    - link: https://jobs.careerbeacon.com/details/juniorintermediate-firmware-engineer/1861591
      remote: false
      title: Junior/Intermediate Firmware Engineer
- company: bluedrop
  jobs:
    current: []
    previous:
    - link: https://bluedropism.com/intermediate-dev-ops-engineer-jan-2023/
      remote: false
      title: Intermediate DevOps Engineer
- company: opasmobile
  jobs:
    current: []
    previous:
    - link: https://technl.ca/job/opas-mobile-st-johns-nl-remote-options-full-time-contract-part-time-temporary-junior-intermediate-backend-developer-nodejs/
      remote: false
      title: Junior/Intermediate Backend Developer (NodeJS)
    - link: https://technl.ca/job/opas-mobile-st-johns-nl-remote-options-full-time-contract-part-time-temporary-junior-intermediate-react-native-developer/
      remote: false
      title: Junior/Intermediate React Native Developer
- company: sequencebio
  jobs:
    current: []
    previous:
    - link: https://sequencebio.bamboohr.com/careers/54
      remote: true
      title: Bioinformatician
    - link: https://sequencebio.bamboohr.com/careers/53
      remote: true
      title: Computational Biologist
    - link: https://sequencebio.bamboohr.com/careers/48
      remote: true
      title: Security Analyst
    - link: https://sequencebio.bamboohr.com/careers/49
      remote: true
      title: Cloud Developer
    - link: https://sequencebio.bamboohr.com/careers/46
      remote: true
      title: Web Application Developer
    - link: https://sequencebio.bamboohr.com/careers/50
      remote: true
      title: Salesforce Developer
    - link: https://sequencebio.bamboohr.com/careers/47
      remote: true
      title: Experienced AWS Infrastructure Engineer
- company: milkmoovement
  jobs:
    current: []
    previous:
    - link: https://jobs.lever.co/milk-moovement/f03643f5-2690-4bb3-a8f8-32870792a4a2
      remote: true
      title: Senior Full Stack Developer
    - link: https://jobs.lever.co/milk-moovement/d21c6a6a-3295-41ce-ab1b-bff880c92a84
      remote: true
      title: Full Stack Developer III
- company: vmt
  jobs:
    current: []
    previous:
    - link: https://www.virtualmarine.ca/careers
      remote: false
      title: Game Developer
    - link: https://www.virtualmarine.ca/careers
      remote: false
      title: Software Developer
    - link: https://www.virtualmarine.ca/careers
      remote: false
      title: Software Developer - Machine Learning
- company: inspectar
  jobs:
    current: []
    previous:
    - link: https://www.inspectar.com/career/qa-engineer-co-op-student
      remote: false
      title: QA Engineer CO-OP Student
    - link: https://www.inspectar.com/career/software-developer-co-op-student
      remote: false
      title: Software Developer CO-OP Student
    - link: https://www.inspectar.com/career/c-sharp-developer
      remote: false
      title: C# Developer
    - link: https://www.inspectar.com/career/sr-unity-developer
      remote: false
      title: Senior Unity Developer
- company: easternhealth
  jobs:
    current: []
    previous:
    - link: https://employment.easternhealth.ca/eRecruit/VacancyDetail.aspx?VacancyUID=000000089318
      remote: true
      title: Computer Programmer/Analyst
- company: strobeltek
  jobs:
    current: []
    previous:
    - link: https://strobeltek.com/careers/
      remote: false
      title: Software Engineer/Mid Electrical
    - link: https://strobeltek.com/careers/
      remote: false
      title: Senior Software Developer
- company: bluecross
  jobs:
    current: []
    previous:
    - link: https://jobs.medaviebc.ca/job/_/559366117/
      remote: true
      title: Test Automation Architect
- company: otherocean
  jobs:
    current: []
    previous:
    - link: https://otherocean.com/jobs/Senior_Programmer.pdf
      remote: true
      title: Senior Programmer
- company: rally
  jobs:
    current: []
    previous:
    - link: https://rallynow.freshteam.com/jobs/wq8HSn3O1Tdx/full-stack-engineer
      remote: true
      title: Full-Stack Engineer
- company: compusult
  jobs:
    current: []
    previous:
    - link: https://www.compusult.com/web/guest/careers
      remote: false
      title: Software Developers
- company: avalonholo
  jobs:
    current: []
    previous:
    - link: https://www.avalonholographics.com/careers
      remote: false
      title: FPGA Designer
    - link: https://www.avalonholographics.com/careers
      remote: false
      title: Software Engineer
- company: ioa
  jobs:
    current: []
    previous:
    - link: https://ioass.com/careers-1
      remote: false
      title: Programmer / Analyst
newPostings: true
updateDate: 2023-04-06
