duplication:
  ignored_urls:
    - 'http://www.smartice.org/jobs/'
    - 'https://www.avalonholographics.com/careers'
    - 'https://www.bluedriver.com/about-us/careers'
    - 'https://www.bullseyebranding.ca/opportunities/'
    - 'https://www.compusult.com/web/guest/careers'
    - 'https://www.sequencebio.com/careers'
    - 'https://www.virtualmarine.ca/careers'
    - 'https://us.bluedriver.com/pages/careers'
    - 'https://strobeltek.com/careers/'
