name: Slack Post Bot

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      max-parallel: 4
      matrix:
        node-version: [10.x]
      
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: |
          git clone https://github.com/CTS-NL/slack-post-bot.git
          cd slack-post-bot
          ls ../
          pwd
          npm ci
          node src/bin/cts.js jobs ../_data/ 2019-10-24
        env:
          SLACK_POST_URL: ${{ secrets.SLACK_POST_URL }}
